### ISSUE TITLE
[MySQL] Error: Too many connections

### ISSUE THREAD

**Issue by rigobcastro** [ForbesLindesay/atdatabases#32] opened 2019-09-23 18:14 UTC
Hi everybody, I need to help.

I have the classic "too many connections" error. I know how to release connections using mysql2 library but here I don't know how to.

Can you tell me how can I release connections from pool?

Thanks!

**Comment by ForbesLindesay** [comment] 2019-09-28 00:19
After seeing this, I did have a quick review of the code and spotted #33. If that was what was causing the issue, it should be fixed after 1.0.3.

Failing that, I'm not sure what exactly would cause this:

* If you use `db.task` to get a connection, it should be released automatically when the task completes: https://github.com/ForbesLindesay/atdatabases/blob/74ca74bf3b6e82877fd21390b018a154e669ccc0/packages/mysql/src/index.ts#L77
* If you use `db.tx` to get a connection, it should be released automatically once the transaciton is committed/rolled-back: https://github.com/ForbesLindesay/atdatabases/blob/74ca74bf3b6e82877fd21390b018a154e669ccc0/packages/mysql/src/index.ts#L97-L103
* If you just use query, we never explicitly get a connection in the first place.

Do you think maybe you could produce a test case that demonstrates this "Too many connections" error? To run the tests, you just need `docker` and then you ran run `yarn && yarn test`

**Comment by ForbesLindesay** [comment] 2019-11-26 14:15
Since I haven't seen any other reports of this, I'll close this. If anyone can provide a sample repo that reproduces the issue, please open a fresh issue referencing this one and I'd be happy to investigate further.

**Closed by ForbesLindesay** 2019-11-26 14:15 UTC
Labels: MySQL
